### PR TITLE
Update for 102

### PR DESCRIPTION
**Pull request by jobisoft**
I saw that the core changes to the compose window make it difficult to get your Emoji sidebar at the correct position in 102.

This PR is moving away from the sidebar and uses a composeAction instead. It is not yet perfect, but might help you to move further into that direction.

It introduces the concept of composeScripts, which live inside the editor and receive commands from the popup to insert text. I have not yet found a way to add the emoji to the subject line, since I was not able to detect its active focus. We can try to figure that out later, if you want to keep going into that direction.

Since the composeAction is a pure WebExtension concept, you do not need the WindowListener API for it anymore. I renamed the no longer needed files to start with an underscore. I did not touch customizeToolbar.js and messenger.js, but I believe you can remove them altogether and get rid of the WindowListener API and turn your add-on into a pure WebExtension.

I also did not understand the history function and since it threw a CSP violation (because the loaded jQuery is doing some crazy stuff), I had to comment it out. We need to convert that part to vanilla JS.

I also did not understand your build system, so I made the changes to the files inside of the thunderbird folder only. You might have to move the changes elsewhere.

I will be happy to continue assisting you with this update, if you wish.

### CODE REVIEW

**Comment by mganss** [comment]
Huge thanks @jobisoft for helping with this!

- I've removed all linq.js dependent code including the lines in the history function and replaced them with vanilla JS. Linq.js is a port of [LINQ](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/) to JS.
- I had to store the history in storage.local instead storage.sync because I kept getting exceptions. 🤷🏻 
- I think the toolbar button needs to be on the main toolbar because the format toolbar doesn't show if it's plain text.

Except for the subject issue and some cleanup this seems almost ready to merge.

A downside of the composeAction is that now you need two clicks to insert an emoji. But I'm willing to accept that if it's the path of least resistance going forward.

Do you think there is a way to control the width of the popup?

Other issues:
- Use monochrome icon on the toolbar
- Show tooltips when hovering over an emoji icon

**Comment by jobisoft** [comment]
> I think the toolbar button needs to be on the main toolbar because the format toolbar doesn't show if it's plain text.

Good catch. Since `maintoolbar` is the default, you do not need to specify it at all.

> Do you think there is a way to control the width of the popup?

You can add a width statement to emoji.css, like

```
body {
    background-color: inherit;
    width: 250px;
}
```

**Comment by jobisoft** [comment]
I tried to have a go at toolstips, but that is "not a thing" anymore. There are css approaches using `:before`, `:hover` and `content: attr(...)` but since the tooltip divs will overlap due to the dense nature of your icon display, it will trigger the wrong tooltip. 

If you want to show a name, maybe have a dedicated space/area in the popup, which shows the name of the currently hovered icon?

**Comment by mganss** [comment]
> You can add a width statement to emoji.css, like
> 
> ```
> body {
>     background-color: inherit;
>     width: 250px;
> }
> ```

This works but always adds a horizontal scrollbar if a vertical scrollbar appears. This happens on all categories because the list of emojis is long, but doesn't happen on the history tab if you only have a few recent emojis. Perhaps this is just a simple CSS issue 🤷🏻 

The monochrome icons are there now, but I've encountered some issues:
- As the icon is an SVG, it shouldn't be necessary to add separate icons for light/dark but the `context-fill` color in dark mode is dark, too, so this doesn't work (it used to in previous TB versions)
- In `theme_icons` TB seems to pick the opposite theme icon from the `dark` and `light` entries, i.e. in dark mode the `light` icon is used and vice versa.

Still open:
- Tootips (`title` doesn't work)
- Subject

@jobisoft Can you help with these issues?

**Comment by jobisoft** [comment]
@context-fill: I am no expert here, but I *think* there is a difference in capabilities for core and webext OR something changed in TB102. Can you check if the icon is correctly displayed as webext in TB91?

@dark/light: From the documentation:

_Specifies dark and light icons to be used with themes. The light icon is used on dark backgrounds and vice versa. Note: The default theme uses the default_icon for light backgrounds (if specified)._

https://webextension-api.thunderbird.net/en/102/browserAction.html

So that is expected. There are no "dark" and "light" themes, the icon is picked based on the background colour it is displayed.

@tooltips. See https://github.com/mganss/EmojiAddIn/pull/53#issuecomment-1162886029

@subject: Hm. Can you check, if the popup script can call an Experiment function to retrieve the focus state of the subject field and use that to determine, whether the selected emoji shoud be added to the subject or the composer?

**Comment by mganss** [comment]
> @context-fill: I am no expert here, but I _think_ there is a difference in capabilities for core and webext OR something changed in TB102. Can you check if the icon is correctly displayed as webext in TB91?

In TB91, the CSS class `.toolbarbutton-1` had

```css
.toolbarbutton-1 {
    fill: var(--toolbarbutton-icon-fill, currentColor);
    fill-opacity: var(--toolbarbutton-icon-fill-opacity);
}
```

In TB102 it has

```css
.toolbarbutton-1 {
  fill: color-mix(in srgb, var(--toolbarbutton-icon-fill, currentColor) 20%, transparent);
  stroke: var(--toolbarbutton-icon-fill, currentColor);
  fill-opacity: var(--toolbarbutton-icon-fill-opacity);
}
```

So I just set `fill="current-stroke` in the SVG image and now it works beautifully. No need for theme-icons.

> So that is expected. There are no "dark" and "light" themes, the icon is picked based on the background colour it is displayed on.

OK, got it.

> @subject: Hm. Can you check, if the popup script can call an Experiment function to retrieve the focus state of the subject field and use that to determine, whether the selected emoji shoud be added to the subject or the composer?

Will investigate.

**Comment by mganss** [comment]
> @subject: Hm. Can you check, if the popup script can call an Experiment function to retrieve the focus state of the subject field and use that to determine, whether the selected emoji shoud be added to the subject or the composer?

@jobisoft I can call an experiment function from the popup script but how do I access the compose window document from there? Also, how do I debug the experiment function? Can't find the script in neither the global developer toolbox nor the extension toolbox tab.

**Comment by jobisoft** [comment]
The implemetation.js file is only visible in the debugger, after it has been loaded. I can show you that later on. For now, I would like to find a solution for the subject without an additional Experiment.

The compose script can detect its blur event, so it knows when it looses focus. Would that info be enough to detect that as "subject has focus"? So whenever the message itself has not focus, the emoji will be added to the subject field (even if the to field might have focus).

Or do you want to know for sure, that the subject has focus? Then we have to use an Experiment.

**Comment by mganss** [comment]
That would be enough for me, though I don't mind going the experiment route either. I've tested the blur and focus events and they do work, however I'm getting a blur event before the toolbar button that opens the popup is pressed, too. So I'm not sure how to distinguish between losing focus because the focus moves to another input field and the case where the focus is lost because the toolbar button is pressed.

**Comment by jobisoft** [comment]
@The blur from the popup: Yes, we would have to log timestamps and if the last blur happened "just before" the popup was opened, we know the mail editor had focus.

Users are starting to oppose the full access permission (even though that was standard 2 years ago) so I try to use techniques which do not need Experiments.

Do you need help with storing the time of the last blur event in the compose script and return it to the popup if it requests that information?

**Comment by mganss** [comment]
> @the blur from the popup: Yes, we would have to log timestamps and if the last blur happened "just before" the popup was opened, we know the mail editor had focus.

Relying on timing seems hacky, but ok, let's try that.

> Users are starting to oppose the full access permission (even though that was standard 2 years ago) so I try to use techniques which do not need Experiments.

Good point. I've received a number of requests/complaints about that, too. Would be nice to get rid of that.

> Do you need help with storing the time of the last blur event in the compose script and return it to the popup if it requests that information?

Sure, I'd be glad if you could assist.

**Comment by jobisoft** [comment]
This looks nice, the blur timestamp is how I would have done it also. Only on the popup, I would not use the focus, but the load or DOMContentloaded event. Any specific reason you use the focus event?

Things which could be improved:
- the former tooltip is shown below the category icons, but its space is not reserved, the icons wobble up and down when tooltip is shown or not shown. Maybe it is enough to use visibility: hidden instead display: none (https://www.w3schools.com/cssref/pr_class_visibility.asp)

- the category icons do not filter the view, was their intention to reduce the shown icons to "food" or "numbers"? Does that work for you? I always see all icons.

**Comment by jobisoft** [comment]
I just saw that the search also does not work for me on Windows. Does it work for you?

**Comment by mganss** [comment]
@jobisoft I believe the issues with the tooltip, categories, and search stem from the fact that TaskPane.css is not committed to Git because it's copied during the build process from AddInCompose/TaskPane directory. If you don't want to run Gulp, just copy it over to chrome/content.

I chose focus because I wasn't even aware that I could use the load event :) It appears that the load event occurs even before the blur event so the timing logic no longer applies. Also, and this applies to blur/focus as well, I'm not sure how to solve the case where the compose tab has never had focus (yet), e.g. when the user has just opened the compose window. Should the extension initially insert into the subject until the user has given focus to the compose tab for the first time?

**Comment by mganss** [comment]
@jobisoft I think I have found a good solution. As the load event occurs prior to the blur event, the compose script can just return the current result of `document.hasFocus()` without the need for any timestamp hackery.

The initial state will be to insert into the subject 🤷🏻

**Comment by jobisoft** [comment]
> I chose focus because I wasn't even aware that I could use the load event :) It appears that the load event occurs even before the blur event so the timing logic no longer applies.

If it works, then release a version to serve your users.

For your next version: if load is always before blur, you could track the focus state instead of the blur state, to eliminate the timestamp, but I would ask users on all platforms if that really works.

Regarding initial open: That is a design choice you will have to make. I would add the emoji to the compose window, I think.

**Comment by jobisoft** [comment]
> For your next version: if load is always before blur, you could track the focus state instead of the blur state, to eliminate the timestamp, but I would ask users on all platforms if that really works.

Haha, you had the same idea. Nice. Do you have mac users? I can test on windows and linux.

**Comment by mganss** [comment]
I can test on Mac as well. It would be great if you could test on Linux.

I think I'll leave the initial state as is for now because otherwise the initial state would probably have to differ from the "default" state where neither compose nor subject have the focus.

**Comment by jobisoft** [comment]
Can you post a zipped version of the final extension, so I can test the real thing, avoiding build issues on my side?

**Comment by mganss** [comment]
[emoji.zip](https://github.com/mganss/EmojiAddIn/files/9041364/emoji.zip)

**Comment by jobisoft** [comment]
It works!

Something for the next version: Fix the categories and the tooltip display at the top, so it does not scroll out of the view.

**Comment by mganss** [comment]
It didn't work on macOS. Uh 🙄 Now I'm using the blur event in the compose script as a fallback and this works on macOS, too.

I also implemented the sticky top navigation but it wasn't easy because I had to set the div's background color using JS. The CSS variables that are visible in the debugger for other windows don't seem to be available. Also, I don't know how to show the popup's HTML in the developer tools because it closes if the developer tools get focus.

**Comment by jobisoft** [comment]
There is a window selector in the top right corner:
image

**Comment by jobisoft** [comment]
Ah, sorry, that is a WebExt, you see that only in the WebExt inspector ... Go to debug add-ons and inspect your add-on. Then a new tab is opened. It should have the same elements as the big inspector.

**Comment by Lidgeu** [comment]
For your info, I installed the xpi (1.102.9) given above under (old good) WIN7 64bit, TB 102.1, dark mode.
Its works perfectly ... except the visibility of Emoj icon itself.
With cursor "far", hidden : TBEmoj-1
With cursor very close, an empty square shows up : TBEmoj-2
At click on this square, WORKS : TBEmoj-3

When this detail (due to dark mode ?) is solved, I think too you may ship :o)

**Comment by jobisoft** [comment]
@Lidgeu : I assume this is a bug in TB and not primarily of the add-on. Or the add-on is using a feature not supported by Win 7. Can you check - in your specific configuration - if [Quicktext](https://addons.thunderbird.net/addon/quicktext/) has the same issue?

@mganss : Are you using an SVG for the icon? You could revert to theme_icons and use dedicated png icons for dark and light theme, if you want to address this issue.

**Comment by mganss** [comment]
@jobisoft Yes, the button image is an SVG. It seems the other toolbar button images (like the attachment icon) are SVGs, too, though.
@Lidgeu Does the icon show in light mode?

**Comment by Lidgeu** [comment]
@jobisoft 
FYI.
Every day, when I shutdown my PC, I run CCleaner. So I did it last evening.
When I restarted TB today, this "A mettre à jour" disappeared :-). So you may discard this feedback.
Pierre

**Comment by mganss** [comment]
So it seems that rendering SVGs generally works. My guess is that it has to do with TB's theme colors on Windows 7, particularly the `context-stroke` and `context-fill` colors. I'm leaning towards not trying to fix this.

**Comment by Lidgeu** [comment]
I'm pretty sure a colored icon will appear but you are the boss. It's your
decision 😉 !!
Thx to have analyzed the problem 🙂

Le lun. 11 juil. 2022 à 17:01, Michael Ganss ***@***.***> a
écrit :

**Pull request merged**
